production:
  server: "https://test-private-pub-petshuggy.herokuapp.com/faye"

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension.

  secret_token: 998b9df8aeceb2668df74ac19edf8e3420773c1d48b9cf1191b633259393a129
  signature_expiration: 3600 # one day